### ISSUE TITLE
Does this support the Reset pin to the target ?

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [GCY/JLINK-ARM-OB#1]
I don't think its  possible t use this on some MCU's because the target needs to be reset while some SWD commands are sent, in order to remove the read protection and erase the IC e.g. most NXP processors need this ?

**Comment by GCY** [comment]
Yes, it's only TMS and TCK(3-wire mode), if you need to reset your target device,  connect PA1 and reset pin with wire jump.

<img width="499" alt="reset pin pa1" src="https://user-images.githubusercontent.com/433290/68539351-315b7100-03bd-11ea-82ec-fca62321c378.png">


Reference J-LINK full function SWD and JTAG
PA0 Activity LED
PA1 RESET
PA2 SWCLK(TCK)
PA3 SWO(TDO)
PA4 SWDIO(TMS)
PA9 RX
PA10 TX

**Comment by rogerclarkmelbourne** [comment]
Excellent.

Thanks.

**Comment by kaehless** [comment]
Going by your eagle schematic

![image](https://user-images.githubusercontent.com/66507720/83937196-0d0a2a80-a80e-11ea-9f55-19cc2853a49e.png)

@GCY should this be ?

PA2 nRESET
PA3 SWCLK 
PA4 SWDIO

Note: using PA3 (CLK) & PA4 (DIO) seems to work.

You seem to be using PB12 for activity light 

![image](https://user-images.githubusercontent.com/66507720/83937232-6a9e7700-a80e-11ea-87b6-cc18496b06cc.png)

**Comment by kaehless** [comment]
Oh nvm, I saw the JLINK OB datasheet. I misread the schematic, thanks
